language: scala

scala:
   - 2.11.7

jdk:
  - openjdk8

# Intellij versions that are checked in CI:
#
# Usually the list contains least one for each major version between
# "sinceBuild" and "untilBuild" (from build.gradle).

env:
  - IDEA_VERSION=IC-192.5728.98
  - IDEA_VERSION=IC-2020.2

script:
  - ./gradlew --console=plain check verifyPlugin

jobs:
  include:
    - stage: release
      if: tag IS present
      script:
        - ./gradlew --console=plain publishPlugin
