language: scala

scala:
  - 2.13.3

jdk: openjdk11

# Intellij versions that are checked in CI:
#
# Usually the list contains least one for each major version between
# "sinceBuild" and "untilBuild" (from build.gradle).

env:
  - IDEA_VERSION=IC-2021.1
  - IDEA_VERSION=IC-2021.3
  - IDEA_VERSION=IC-2022.1

jobs:
  include:
    - stage: test
      script:
        - ./gradlew --console=plain check verifyPlugin
    - stage: release
      if: tag IS present
      script:
        - ./gradlew --console=plain publishPlugin
