language: scala

scala:
  - 2.12.12

jdk: openjdk11

jobs:
  include:
    - stage: test
      script:
        - ./gradlew --console=plain check verifyPlugin
    - stage: release
      if: tag IS present
      script:
        - ./gradlew --console=plain publishPlugin
