language: scala

scala:
   - 2.11.12

jdk:
  - oraclejdk8

env:
  - IDEA_VERSION=IC-2017.3.5
  - IDEA_VERSION=IC-2018.1.6
  - IDEA_VERSION=IC-183.4284.36
  - IDEA_VERSION=IC-191.6183.87

script:
  - ./gradlew --console plain check verifyPlugin

jobs:
  include:
    - stage: release
      if: tag IS present
      script:
        - ./gradlew --console plain publishPlugin