{
  parserClass="amailp.parser.RobotParser"
  stubParserClass="amailp.parser.GeneratedParserUtilBase"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Robot"
  psiImplClassSuffix="Impl"
  psiPackage="amailp.psi"
  psiImplPackage="amailp.psi.impl"

  elementTypeHolderClass="amailp.psi.RobotTypes"
  elementTypeClass="amailp.psi.RobotElementType"
  tokenTypeClass="amailp.psi.RobotTokenType"
}

simpleFile ::= item_*

private item_ ::= (property|COMMENT|CRLF)

property ::= (KEY? SEPARATOR VALUE?) | KEY